apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi  # Reverting to 1Gi as many storage classes have a 1Gi minimum
