apiVersion: v1
kind: Service
metadata:
  name: last-person-standing-service
spec:
  type: ClusterIP
  selector:
    app: last-person-standing
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
